name: Debug Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug: Check SERVERLESS_ACCESS_KEY presence
        run: if [ -z "$SERVERLESS_ACCESS_KEY" ]; then echo "NOT set"; exit 1; else echo "set"; fi
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
